"""empty message

Revision ID: af6e662cc439
Revises: 75aabb75fb6a
Create Date: 2021-08-28 17:10:04.596670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6e662cc439'
down_revision = '75aabb75fb6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'todo', 'user', ['owner_id'], ['id'])
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'todo', type_='foreignkey')
    # ### end Alembic commands ###
